name: "Get Camunda Bearer Token"
description: "Fetches a fresh Camunda OAuth token using client credentials"
inputs:
  client_id:
    required: true
  client_secret:
    required: true
  audience:
    required: true

outputs:
  token:
    description: "The generated bearer token"

runs:
  using: "composite"
  steps:
    - name: Get Token
      id: get-token
      shell: bash
      run: |
        RESPONSE=$(curl -s --request POST \
          --url https://login.cloud.camunda.io/oauth/token \
          --header 'content-type: application/json' \
          --data '{
            "grant_type":"client_credentials",
            "client_id":"${{ inputs.client_id }}",
            "client_secret":"${{ inputs.client_secret }}",
            "audience":"${{ inputs.audience }}"
          }')

        echo "TOKEN RESPONSE: $RESPONSE"

        ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
        if [[ "$ACCESS_TOKEN" == "null" || -z "$ACCESS_TOKEN" ]]; then
          echo "❌ Failed to extract access_token"
          exit 1
        fi

        # echo "::add-mask::$ACCESS_TOKEN"
        echo "DEBUG: Token is --> $ACCESS_TOKEN"
        echo "token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT