name: "Get Camunda Bearer Token"
description: "Fetches a fresh Camunda OAuth token using client credentials"
inputs:
  client_id:
    required: true
  client_secret:
    required: true
  audience:
    required: true

outputs:
  token:
    description: "The generated bearer token"

runs:
  using: "composite"
  steps:
    - name: Get Token
      id: get-token
      shell: bash
      run: |
        echo "DEBUG: client_id=$(echo 'YOUR_REAL_CLIENT_ID' | base64)"
        echo "DEBUG: client_secret=$(echo 'YOUR_REAL_CLIENT_SECRET' | base64)"
        echo "DEBUG: audience=$(echo 'YOUR_REAL_AUDIENCE' | base64)"
        RESPONSE=$(curl -s --request POST \
        --url https://login.cloud.camunda.io/oauth/token \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --data 'grant_type=client_credentials' \
        --data "client_id=$(echo -n 'MFtxiv0TSBxUrBtTYzIwpZ0Z5elzJQNE')" \
        --data "client_secret=$(echo -n 'rnzbiYvJYjGDWf4.yRfU~2QKpnlljFOXxeuChEzECpZX4gNzZtEAYJU9cRwYnEyM')" \
        --data "audience=$(echo -n 'zeebe.camunda.io')")

        ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
        echo "token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT