name: Get Camunda Bearer Token
description: Authenticates with Camunda and returns a fresh access token
runs:
  using: "composite"
  steps:
    - name: Get Token
      id: token
      shell: bash
      run: |
        RESPONSE=$(curl -s --request POST \
          --url https://login.cloud.camunda.io/oauth/token \
          --header 'content-type: application/json' \
          --data '{
            "grant_type":"client_credentials",
            "client_id":"${{ secrets.CAMUNDA_CLIENT_ID }}",
            "client_secret":"${{ secrets.CAMUNDA_CLIENT_SECRET }}",
            "audience":"${{ secrets.CAMUNDA_AUTH_AUDIENCE }}"
          }')

        echo "TOKEN RESPONSE: $RESPONSE"

        ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
        if [[ "$ACCESS_TOKEN" == "null" || -z "$ACCESS_TOKEN" ]]; then
          echo "❌ Failed to extract access_token"
          exit 1
        fi

        echo "::add-mask::$ACCESS_TOKEN"
        echo "token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT