name: Cleanup Merged Branches

on:
  workflow_run:
    workflows: ["Notify Camunda – Dev PR Merge Event"]
    types: [completed]

jobs:
  delete-merged:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Delete merged branch if it matches allowed prefixes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          BRANCH_NAME="${{ github.event.workflow_run.head_branch }}"

          echo "🔍 Candidate for deletion: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" =~ ^(feature/|bugfix/|hotfix/|release/|chore/|docs/|test/|refactor/) ]]; then
            echo "Deleting branch: $BRANCH_NAME"
            curl -X DELETE \
              -H "Authorization: Bearer $GH_PAT" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME
          else
            echo "Skipping branch $BRANCH_NAME (prefix not allowed)"
          fi