name: Delete Merged Feature Branch

on:
  workflow_run:
    workflows: ["Notify Camunda BPMN on PR Merge"]
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete merged branch
        run: |
          BRANCH_NAME=${{ github.event.workflow_run.head_branch }}
          if [[ "$BRANCH_NAME" =~ ^(feature/|bugfix/|hotfix/|release/|chore/|docs/|test/|refactor/|updated-) ]]; then
            echo "Deleting branch: $BRANCH_NAME"
            curl -X DELETE \
              -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME
          else
            echo "Branch $BRANCH_NAME not in prefix list, skipping deletion."