name: Camunda CI/CD Deployment (Stage)

on:
  push:
    branches:
      - stage

jobs:
  deploy-stage:
    name: Deploy to Camunda Cluster – Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Stage Branch
        uses: actions/checkout@v4
        with:
          ref: stage

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set Camunda Stage Secrets
        run: |
          echo "CLIENT_ID=${{ secrets.CAMUNDA_STAGE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "CLIENT_SECRET=${{ secrets.CAMUNDA_STAGE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "CLUSTER_ID=${{ secrets.CAMUNDA_STAGE_CLUSTER_ID }}" >> $GITHUB_ENV

      - name: Get Zeebe Bearer Token
        id: get_token
        uses: ./actions/get-bearer-token
        with:
          client_id: ${{ env.CLIENT_ID }}
          client_secret: ${{ env.CLIENT_SECRET }}
          audience: ${{ secrets.CAMUNDA_AUTH_AUDIENCE }}

      - name: Prepare Model Files
        run: |
          mkdir -p deploy
          cp src/main/resources/models/*.bpmn deploy/ || true
          cp src/main/resources/models/*.form deploy/ || true
          cp src/main/resources/models/*.dmn deploy/ || true

      - name: Deploy to Camunda Stage Cluster
        run: |
          FILES=$(find deploy -type f)
          CURL_ARGS=()
          for FILE in $FILES; do
            CURL_ARGS+=(-F "resources=@$FILE")
          done

          curl -X POST "https://bru-2.zeebe.camunda.io:443/$CLUSTER_ID/v2/deployments" \
            -H "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
            -H "Content-Type: multipart/form-data" \
            "${CURL_ARGS[@]}"