name: Notify Camunda BPMN on Test Success

on:
  check_suite:
    types: [completed]

jobs:
  notify-bpmn:
    if: github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.event.check_suite.head_branch }}

    steps:
      - name: Notify Camunda
        run: |
          curl -X POST https://bru-2.connectors.camunda.io/2a1d22c6-5683-423b-9d58-0ff0a77fcb86/inbound/checkMergeRequestStatus \
            -H "Content-Type: application/json" \
            -d "{\"branch\": \"${BRANCH_NAME}\"}"