name: Notify Camunda on CI Success

on:
  check_suite:
    types: [completed]

jobs:
  notify-camunda:
    if: github.event.check_suite.conclusion == 'success' && github.event.check_suite.pull_requests != []
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Notify Camunda - Merge Status Passed
        run: |
          curl -X POST https://bru-2.connectors.camunda.io/2a1d22c6-5683-423b-9d58-0ff0a77fcb86/inbound/checkMergeRequestStatus \
            -H "Content-Type: application/json" \
            -d '{
                  "status": "success",
                  "branch": "'${{ github.head_ref }}'",
                  "repository": "'${{ github.repository }}'",
                  "commit": "'${{ github.sha }}'",
                  "initiator": "GitHub Actions"
                }'