name: Notify Camunda BPMN on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  notify-camunda:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Notify Camunda BPMN
        run: |
          curl -X https://bru-2.connectors.camunda.io/2a1d22c6-5683-423b-9d58-0ff0a77fcb86/inbound/checkMergeRequestStatus \
            -H "Content-Type: application/json" \
            -d '{
              "pull_request": {
                "number": ${{ github.event.pull_request.number }},
                "head": {
                  "ref": "${{ github.event.pull_request.head.ref }}"
                }
              }
            }