name: Notify Camunda BPMN on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  notify-camunda:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Zeebe Bearer Token
        id: get_token
        uses: ./actions/get-bearer-token
        with:
          client_id: ${{ secrets.CAMUNDA_CLIENT_ID }}
          client_secret: ${{ secrets.CAMUNDA_CLIENT_SECRET }}
          audience: ${{ secrets.CAMUNDA_AUTH_AUDIENCE }}

      - name: Publish Message to Camunda
        run: |
          curl -X POST https://bru-2.zeebe.camunda.io:443/${{ secrets.CAMUNDA_CLUSTER_ID }}/v2/messages/publication \
          -H "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
          -H "Content-Type: application/json" \
          -d '{
          "name": "mergeRequestPassed",
          "correlationKey": "merged1234",
          "variables": {
            "pull_request_number": "${{ github.event.pull_request.number }}",
            "branch": "${{ github.event.pull_request.head.ref }}"
          },
          "timeToLive": 360000
          }'