name: Notify Camunda BPMN on Test Success

on:
  check_suite:
    types: [completed]

jobs:
  notify-bpmn:
    if: github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Notify Camunda
        run: |
          curl -X POST https://your-camunda-webhook \
            -H "Content-Type: application/json" \
            -d '{"branch": "${{ github.event.check_suite.head_branch }}"}'